device: cpu # cpu, cuda:0 ...
num_workers: 4 #default
model_dir: None
dataset:
  root_dir: datasets/VOC2012
  name_list_dir: datasets/voc
  num_classes: 21
  crop_size: 320
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

work_dir:
  dir: work_dir_voc
  ckpt_dir: checkpoints
  pred_dir: predictions
  segs_dir: segs
  tb_logger_dir: tb_logger

train:
#  split: train_aug
  split: train_aug_mac
  samples_per_gpu: 4 #4 #2
  max_iters: 40000
#  max_iters: 10
  cam_iters: 2000
#  eval_iters: 2000
  eval_iters: 2
#  log_iters: 200
  log_iters: 2


val:
#  split: train
  split: train_mac

optimizer:
  type: AdamW
  learning_rate: 2e-4 #2e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 50 #1500
  warmup_ratio: 1e-6
  power: 1.0

clip_init:
  clip_pretrain_path: clip/pretrained/ViT-B-16.pt
  embedding_dim: 256
  in_channels: [768, 768,768,768]
